### ISSUE TITLE
Support for older Android versions

### ISSUE THREAD

**Issue by richardbrinkman** [Data4All/Data4All#8]
The current version of Data4All requires Android 4.1 and up. Is there any possibility to also allow older Android versions? My phone runs Android 2.2 and cannot be updated. The project claims to provide an application for EVERYONE not just people with some hightech state of the art phone.

**Comment by tbrose** [comment]
At the moment our Application supports around 90% of all Devices.
We use Jelly Bean and up because of the animation-library used for several UI-elements (e.g. the crosshair in the camera)
In this case "everyone" means "almost everyone", but feel free to fork the repository and edit the ViewAnimators in order to support older versions than 4.1
